<?php
/**
 * Title: Faq
 * Slug: pixetiq/pixetiq-faq
 * Categories: about, banner
 * Viewport width: 1400
 */
?>

<!-- wp:group {"metadata":{"name":"Faq","categories":["about","banner"],"patternName":"pixetiq/pixetiq-faq"},"align":"full","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"backgroundColor":"bg-normal","layout":{"type":"default"}} -->
<div class="wp-block-group alignfull has-bg-normal-background-color has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"metadata":{"name":"FAQs"},"align":"full","style":{"spacing":{"padding":{"top":"0px","bottom":"0px","left":"0px","right":"0px"},"margin":{"top":"0","bottom":"0"},"blockGap":"0px"},"elements":{"link":{"color":{"text":"var:preset|color|contrast"}}}},"textColor":"contrast","layout":{"type":"constrained","justifyContent":"center"}} -->
<div class="wp-block-group alignfull has-contrast-color has-text-color has-link-color" style="margin-top:0;margin-bottom:0;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"wide","layout":{"type":"constrained","justifyContent":"center"}} -->
<div class="wp-block-group alignwide"><!-- wp:heading {"textAlign":"center","style":{"typography":{"fontSize":"38px","fontStyle":"normal","fontWeight":"600"},"spacing":{"margin":{"bottom":"30px"}},"elements":{"link":{"color":{"text":"var:preset|color|dark"}}}},"textColor":"dark","fontFamily":"body"} -->
<h2 class="wp-block-heading has-text-align-center has-dark-color has-text-color has-link-color has-body-font-family" style="margin-bottom:30px;font-size:38px;font-style:normal;font-weight:600"><?php esc_html_e('Frequently asked questions', 'pixetiq');?></h2>
<!-- /wp:heading -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"20px","bottom":"20px","left":"30px","right":"30px"}},"border":{"radius":"6px"}},"backgroundColor":"white","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-white-background-color has-background" style="border-radius:6px;padding-top:20px;padding-right:30px;padding-bottom:20px;padding-left:30px"><!-- wp:details {"className":"is-style-arrow-icon-details","style":{"spacing":{"margin":{"top":"0"}},"border":{"top":{"width":"0px","style":"none"},"right":{"width":"0px","style":"none"},"bottom":{"color":"var:preset|color|border-color","style":"solid","width":"1px"},"left":{"width":"0px","style":"none"}},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|dark"}}}},"textColor":"dark","fontFamily":"body"} -->
<details class="wp-block-details is-style-arrow-icon-details has-dark-color has-text-color has-link-color has-body-font-family" style="border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--border-color);border-bottom-style:solid;border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;font-size:18px;font-style:normal;font-weight:500"><summary><?php esc_html_e('Is there a free trial available?', 'pixetiq');?></summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"400"},"elements":{"link":{"color":{"text":"var:preset|color|gray"}}}},"textColor":"gray","fontFamily":"body"} -->
<p class="has-gray-color has-text-color has-link-color has-body-font-family" style="font-size:16px;font-style:normal;font-weight:400"><?php esc_html_e('Yes, you can try us for free for 30 days. If you want, we’ll provide you with a free, personalized 30-minute onboarding call to get you up and running as soon as possible.', 'pixetiq');?></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-arrow-icon-details","style":{"spacing":{"margin":{"top":"0"}},"border":{"top":{"width":"0px","style":"none"},"right":{"width":"0px","style":"none"},"bottom":{"color":"var:preset|color|border-color","style":"solid","width":"1px"},"left":{"width":"0px","style":"none"}},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|dark"}}}},"textColor":"dark","fontFamily":"body"} -->
<details class="wp-block-details is-style-arrow-icon-details has-dark-color has-text-color has-link-color has-body-font-family" style="border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--border-color);border-bottom-style:solid;border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;font-size:18px;font-style:normal;font-weight:500"><summary><?php esc_html_e('Can I change my plan later?', 'pixetiq');?></summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"400"},"elements":{"link":{"color":{"text":"var:preset|color|gray"}}}},"textColor":"gray","fontFamily":"body"} -->
<p class="has-gray-color has-text-color has-link-color has-body-font-family" style="font-size:16px;font-style:normal;font-weight:400"><?php esc_html_e('Études offers comprehensive consulting, management, design, and research solutions. Our vision is to be at the forefront of architectural innovation, fostering a global community of architects and enthusiasts united by a passion for creating spaces. Every architectural endeavor is an opportunity to shape the future.', 'pixetiq');?></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-arrow-icon-details","style":{"spacing":{"margin":{"top":"0"}},"border":{"top":{"width":"0px","style":"none"},"right":{"width":"0px","style":"none"},"bottom":{"color":"var:preset|color|border-color","style":"solid","width":"1px"},"left":{"width":"0px","style":"none"}},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|dark"}}}},"textColor":"dark","fontFamily":"body"} -->
<details class="wp-block-details is-style-arrow-icon-details has-dark-color has-text-color has-link-color has-body-font-family" style="border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--border-color);border-bottom-style:solid;border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;font-size:18px;font-style:normal;font-weight:500"><summary><?php esc_html_e('What is your cancellation policy?', 'pixetiq');?></summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"400"},"elements":{"link":{"color":{"text":"var:preset|color|gray"}}}},"textColor":"gray","fontFamily":"body"} -->
<p class="has-gray-color has-text-color has-link-color has-body-font-family" style="font-size:16px;font-style:normal;font-weight:400"><?php esc_html_e('Études offers comprehensive consulting, management, design, and research solutions. Our vision is to be at the forefront of architectural innovation, fostering a global community of architects and enthusiasts united by a passion for creating spaces. Every architectural endeavor is an opportunity to shape the future.', 'pixetiq');?></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-arrow-icon-details","style":{"spacing":{"margin":{"top":"0"}},"border":{"top":{"width":"0px","style":"none"},"right":{"width":"0px","style":"none"},"bottom":{"color":"var:preset|color|border-color","style":"solid","width":"1px"},"left":{"width":"0px","style":"none"}},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|dark"}}}},"textColor":"dark","fontFamily":"body"} -->
<details class="wp-block-details is-style-arrow-icon-details has-dark-color has-text-color has-link-color has-body-font-family" style="border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--border-color);border-bottom-style:solid;border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;font-size:18px;font-style:normal;font-weight:500"><summary><?php esc_html_e('Can other info be added to an invoice?', 'pixetiq');?></summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"400"},"elements":{"link":{"color":{"text":"var:preset|color|gray"}}}},"textColor":"gray","fontFamily":"body"} -->
<p class="has-gray-color has-text-color has-link-color has-body-font-family" style="font-size:16px;font-style:normal;font-weight:400"><?php esc_html_e('Études offers comprehensive consulting, management, design, and research solutions. Our vision is to be at the forefront of architectural innovation, fostering a global community of architects and enthusiasts united by a passion for creating spaces. Every architectural endeavor is an opportunity to shape the future.', 'pixetiq');?></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-arrow-icon-details","style":{"spacing":{"margin":{"top":"0"}},"border":{"top":{"width":"0px","style":"none"},"right":{"width":"0px","style":"none"},"bottom":{"color":"var:preset|color|border-color","style":"solid","width":"1px"},"left":{"width":"0px","style":"none"}},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|dark"}}}},"textColor":"dark","fontFamily":"body"} -->
<details class="wp-block-details is-style-arrow-icon-details has-dark-color has-text-color has-link-color has-body-font-family" style="border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--border-color);border-bottom-style:solid;border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;font-size:18px;font-style:normal;font-weight:500"><summary><?php esc_html_e('How does billing work?', 'pixetiq');?></summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"400"},"elements":{"link":{"color":{"text":"var:preset|color|gray"}}}},"textColor":"gray","fontFamily":"body"} -->
<p class="has-gray-color has-text-color has-link-color has-body-font-family" style="font-size:16px;font-style:normal;font-weight:400"><?php esc_html_e('Études offers comprehensive consulting, management, design, and research solutions. Our vision is to be at the forefront of architectural innovation, fostering a global community of architects and enthusiasts united by a passion for creating spaces. Every architectural endeavor is an opportunity to shape the future.', 'pixetiq');?></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-arrow-icon-details","style":{"spacing":{"margin":{"top":"0"}},"border":{"top":{"width":"0px","style":"none"},"right":{"width":"0px","style":"none"},"bottom":{"color":"var:preset|color|border-color","style":"solid","width":"1px"},"left":{"width":"0px","style":"none"}},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|dark"}}}},"textColor":"dark","fontFamily":"body"} -->
<details class="wp-block-details is-style-arrow-icon-details has-dark-color has-text-color has-link-color has-body-font-family" style="border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--border-color);border-bottom-style:solid;border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;font-size:18px;font-style:normal;font-weight:500"><summary><?php esc_html_e('How do I change my account email?', 'pixetiq');?></summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"400"},"elements":{"link":{"color":{"text":"var:preset|color|gray"}}}},"textColor":"gray","fontFamily":"body"} -->
<p class="has-gray-color has-text-color has-link-color has-body-font-family" style="font-size:16px;font-style:normal;font-weight:400"><?php esc_html_e('Études offers comprehensive consulting, management, design, and research solutions. Our vision is to be at the forefront of architectural innovation, fostering a global community of architects and enthusiasts united by a passion for creating spaces. Every architectural endeavor is an opportunity to shape the future.', 'pixetiq');?></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->